spring.application.name=API-GATEWAY
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Employee Service
spring.cloud.gateway.server.webflux.routes[0].id=employee-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://EMPLOYEE-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/employee-service/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1

# Department Service
spring.cloud.gateway.server.webflux.routes[1].id=department-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://DEPARTMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/department-service/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=1